package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// generateM3UContent generates M3U playlist content as a string
func generateM3UContent(cfg *XtreamConfig) (string, error) {
	LogInfo("Starting M3U generation from Xtream API")
	LogDebug("Xtream API URL: %s", cfg.BaseURL)

	baseURL := strings.TrimRight(cfg.BaseURL, "/")

	LogInfo("Fetching categories from Xtream API...")
	categories, err := getCategories(baseURL, cfg.Username, cfg.Password, cfg.RequestTimeoutSec)
	if err != nil {
		LogError("Failed to fetch categories: %v", err)
		return "", fmt.Errorf("failed to get categories: %w", err)
	}
	LogInfo("Successfully fetched %d categories", len(categories))

	var result strings.Builder

	// Write M3U header
	result.WriteString("#EXTM3U\n")
	result.WriteString(fmt.Sprintf("# Generated by M3UFromXtream Version: %s\n", version))
	result.WriteString(fmt.Sprintf("# Generated on: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	result.WriteString("\n")

	totalStreams := 0
	failedCategories := 0
	skippedStreams := 0

	for i, category := range categories {
		LogDebug("Processing category %d/%d: %s (ID: %s)", i+1, len(categories), category.CategoryName, category.CategoryID)

		streams, err := getStreams(baseURL, cfg.Username, cfg.Password, category.CategoryID, cfg.RequestTimeoutSec)
		if err != nil {
			LogWarn("Failed to fetch streams for category '%s' (ID: %s): %v", category.CategoryName, category.CategoryID, err)
			failedCategories++
			continue // Skip this category but continue with others
		}

		LogDebug("Category '%s' has %d streams", category.CategoryName, len(streams))

		categoryStreamCount := 0
		for _, stream := range streams {
			if stream.Name == "" || stream.StreamType == "" {
				LogDebug("Skipping stream with missing name or type (ID: %d)", stream.StreamID)
				skippedStreams++
				continue
			}

			streamURL := fmt.Sprintf("%s/%s/%s/%d", baseURL, cfg.Username, cfg.Password, stream.StreamID)

			// Clean fields by removing carriage returns and newlines
			cleanEpgChannelID := cleanField(stream.EpgChannelID)
			cleanName := cleanField(escapeM3UField(stream.Name))
			cleanIcon := cleanField(stream.StreamIcon)
			cleanCategoryName := cleanField(escapeM3UField(category.CategoryName))

			// Write M3U entry
			result.WriteString(fmt.Sprintf("#EXTINF:-1 tvg-id=\"%s\" tvg-name=\"%s\" tvg-logo=\"%s\" group-title=\"%s\",%s\n",
				cleanEpgChannelID,
				cleanName,
				cleanIcon,
				cleanCategoryName,
				cleanName))
			result.WriteString(streamURL)
			result.WriteString("\n\n")

			categoryStreamCount++
			totalStreams++
		}

		LogInfo("Category '%s': processed %d streams", category.CategoryName, categoryStreamCount)
	}

	// Log summary
	LogInfo("M3U generation complete - Total streams: %d, Skipped: %d, Failed categories: %d",
		totalStreams, skippedStreams, failedCategories)

	if totalStreams == 0 {
		LogWarn("No streams were successfully processed")
		return "", fmt.Errorf("no streams were successfully processed - check your Xtream API credentials and connection")
	}

	if failedCategories > 0 {
		LogWarn("%d categories failed to process but %d streams were successfully added", failedCategories, totalStreams)
	}

	return result.String(), nil
}

// cleanField removes carriage returns and newlines from a field
func cleanField(field string) string {
	field = strings.ReplaceAll(field, "\r", "")
	field = strings.ReplaceAll(field, "\n", "")
	return field
}

// getCategories retrieves a list of live categories from the specified server
func getCategories(baseURL, username, password string, timeoutSec int) ([]Category, error) {
	url := fmt.Sprintf("%s/player_api.php?username=%s&password=%s&action=get_live_categories",
		baseURL, username, password)

	LogDebug("Fetching categories from: %s", sanitizeURL(url, password))

	client := &http.Client{
		Timeout: time.Duration(timeoutSec) * time.Second,
	}

	resp, err := client.Get(url)
	if err != nil {
		LogError("HTTP request failed for categories: %v", err)
		return nil, fmt.Errorf("HTTP request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		LogError("Categories API returned status: %s (%d)", resp.Status, resp.StatusCode)
		if resp.StatusCode == http.StatusUnauthorized {
			return nil, fmt.Errorf("authentication failed - check username and password")
		}
		return nil, fmt.Errorf("HTTP request failed with status: %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		LogError("Failed to read categories response body: %v", err)
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	LogDebug("Categories response size: %d bytes", len(body))

	var categories []Category
	if err := json.Unmarshal(body, &categories); err != nil {
		LogError("Failed to parse categories JSON: %v", err)
		LogDebug("Response body preview: %s", previewString(string(body), 200))
		return nil, fmt.Errorf("failed to parse JSON response: %w", err)
	}

	return categories, nil
}

// getStreams retrieves a list of live streams for a specified category from the server
func getStreams(baseURL, username, password, categoryID string, timeoutSec int) ([]Stream, error) {
	url := fmt.Sprintf("%s/player_api.php?username=%s&password=%s&action=get_live_streams&category_id=%s",
		baseURL, username, password, categoryID)

	LogDebug("Fetching streams for category %s from: %s", categoryID, sanitizeURL(url, password))

	client := &http.Client{
		Timeout: time.Duration(timeoutSec) * time.Second,
	}

	resp, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("HTTP request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		LogWarn("Streams API returned status: %s (%d) for category %s", resp.Status, resp.StatusCode, categoryID)
		return nil, fmt.Errorf("HTTP request failed with status: %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	var streams []Stream
	if err := json.Unmarshal(body, &streams); err != nil {
		LogDebug("Failed to parse streams JSON for category %s: %v", categoryID, err)
		return nil, fmt.Errorf("failed to parse JSON response: %w", err)
	}

	return streams, nil
}

// escapeM3UField escapes special characters in an M3U field to ensure proper formatting
func escapeM3UField(field string) string {
	if field == "" {
		return ""
	}

	// Escape special characters in M3U fields
	field = strings.ReplaceAll(field, "\"", "\\\"")
	field = strings.ReplaceAll(field, ",", "\\,")
	field = strings.ReplaceAll(field, ":", "\\:")
	return field
}

// sanitizeURL replaces the password in a URL for safe logging
func sanitizeURL(url, password string) string {
	if password == "" {
		return url
	}
	return strings.ReplaceAll(url, password, "***")
}

// previewString returns a preview of a string (truncated if too long)
func previewString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
